version: 2.1
orbs:
  php: circleci/php@1.1.0
  jobs:
  install_composer_packages:
    executor: php/default
    steps:
      - checkout
      - php/install-composer:
          install-version: 1.10.16
      - php/install-packages
orbs:
  php: circleci/php@x.y
version: 2.1
workflows:
  install:
    jobs:
      - install_composer_packages
      jobs:
  install_php:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - php/install-php:
          version: '7.3'
orbs:
  php: circleci/php@x.y
version: 2.1
workflows:
  install:
    jobs:
      - install_php
    
